name: macos_clang

on: [push, pull_request]

jobs:
  macos_clang:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - name: Download Dependencies
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew update
        brew tap homebrew/cask
        brew install pkg-config
        brew install openal-soft
        brew cask install apenngrace/vulkan/vulkan-sdk
    - name: Build Acid
      env:
        CC: clang
        CXX: clang++
      run: |
        cmake --version
        cmake -B Build -G "Xcode" -DCMAKE_BUILD_TYPE=Release
        cmake --build Build
    - name: Run Tests
      run: |
        ctest
