name: windows_msvc

on: [push, pull_request]

jobs:
  windows_msvc:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - uses: lukka/get-cmake@v3.19.0
    - name: Download OpenAL
      run: |
        Invoke-WebRequest -Uri "https://openal-soft.org/openal-binaries/openal-soft-1.21.0-bin.zip" -OutFile openal-soft.zip
        Expand-Archive -Path openal-soft.zip -DestinationPath C:\\
    - name: Download Vulkan
      run: |
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.154.1/windows/VulkanSDK-1.2.154.1-Installer.exe" -OutFile VulkanSDK.exe
        $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();
    - name: Build Acid
      env:
        VULKAN_SDK: "C:\\VulkanSDK\\1.2.154.1"
        OPENALDIR: "C:\\openal-soft-1.21.0-bin"
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake --version
        ninja --version
        cmake -B Build -GNinja -DCMAKE_BUILD_TYPE=Release
        cmake --build Build
    - name: Run Tests
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        ctest
